name: Sync common labels (manually)
description: 'Common build setup for yarn projects'


runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Synchronize labels
      uses: julbme/gh-action-manage-label@v1
      with:
        from: https://raw.githubusercontent.com/Yleisradio/articleteam-gh-actions/main/label-sync/labels.yml
        skip_delete: true
