# https://github.com/marketplace/actions/github-labeler
name: Sync common labels (manually)

on: workflow_dispatch

jobs:
  labels_sync:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run Labeler
        uses: Yleisradio/articleteam-gh-actions/label-sync@main
